// src/config/keys.js
//
// Loads the RSA keypair generated by scripts/generate-keys.js. The private
// key signs access tokens and ID tokens (RS256); the public key — reshaped
// as a JWK — is what /oidc/jwks exposes so child apps can verify tokens
// without ever holding a secret.

const fs = require('fs');
const crypto = require('crypto');
const env = require('./env');

let privateKeyPem;
let publicKeyPem;

try {
  privateKeyPem = fs.readFileSync(env.jwt.privateKeyPath, 'utf8');
  publicKeyPem = fs.readFileSync(env.jwt.publicKeyPath, 'utf8');
} catch (err) {
  // eslint-disable-next-line no-console
  console.error(
    `[keys] Could not read RSA key files (${env.jwt.privateKeyPath}, ${env.jwt.publicKeyPath}).\n` +
      '[keys] Run `node scripts/generate-keys.js` first, or check JWT_PRIVATE_KEY_PATH / JWT_PUBLIC_KEY_PATH in .env.'
  );
  process.exit(1);
}

const publicKeyObject = crypto.createPublicKey(publicKeyPem);
const jwk = {
  ...publicKeyObject.export({ format: 'jwk' }),
  kid: env.jwt.keyId,
  use: 'sig',
  alg: 'RS256',
};

module.exports = {
  privateKeyPem,
  publicKeyPem,
  kid: env.jwt.keyId,
  jwk,
};
